server:
  port: 6001

spring:
  application:
    name: job-portal-user-service


  datasource:
    url: jdbc:mysql://localhost:3306/user_job?useUnicode=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      open-in-view: false
      properties:
        hibernate:
          format_sql: true
